apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: deepiri-ml-team
  # ML Team Configuration - Only services needed for ML development

build:
  local:
    useBuildkit: true
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
    # Cyrex AI Service (for model inference)
    - image: deepiri-dev-cyrex
      context: ./diri-cyrex
      docker:
        dockerfile: Dockerfile
        buildArgs:
          BUILD_TYPE: prebuilt
          BASE_IMAGE: python:3.11-slim
          PYTORCH_VERSION: 2.9.1
          PYTHON_VERSION: 3.11
    
    # Jupyter for data analysis and training
    - image: deepiri-dev-jupyter
      context: ./diri-cyrex
      docker:
        dockerfile: Dockerfile.jupyter
        buildArgs:
          BUILD_TYPE: prebuilt
          BASE_IMAGE: python:3.11-slim
          PYTORCH_VERSION: 2.9.1
          PYTHON_VERSION: 3.11
    
    # Analytics Service (for feature engineering)
    - image: deepiri-dev-platform-analytics-service
      context: ./platform-services
      docker:
        dockerfile: backend/deepiri-platform-analytics-service/Dockerfile

deploy:
  kubectl:
    manifests: []

