apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: deepiri-ai-team
  # AI Team Configuration - Only services needed for AI/ML development

build:
  local:
    useBuildkit: true
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
    # Cyrex AI Service
    - image: deepiri-dev-cyrex
      context: ./diri-cyrex
      docker:
        dockerfile: Dockerfile
        buildArgs:
          BUILD_TYPE: prebuilt
          BASE_IMAGE: python:3.11-slim
          PYTORCH_VERSION: 2.9.1
          PYTHON_VERSION: 3.11
    
    # Jupyter for experimentation
    - image: deepiri-dev-jupyter
      context: ./diri-cyrex
      docker:
        dockerfile: Dockerfile.jupyter
        buildArgs:
          BUILD_TYPE: prebuilt
          BASE_IMAGE: python:3.11-slim
          PYTORCH_VERSION: 2.9.1
          PYTHON_VERSION: 3.11
    
    # Challenge Service (for AI integration testing)
    - image: deepiri-dev-challenge-service
      context: ./platform-services
      docker:
        dockerfile: backend/deepiri-challenge-service/Dockerfile

deploy:
  kubectl:
    manifests: []

